-- Create a new database called 'DOE_DB'
-- Connect to the 'master' database to run this snippet
CREATE DATABASE IF NOT EXISTS DOE_DB;
USE DOE_DB;

-- SCRIPTS TABLE: USER
-- TABLE 'USER'
CREATE TABLE `USER` (
    ID_USER INTEGER NOT NULL AUTO_INCREMENT,
    FULL_NAME VARCHAR(100) NOT NULL,
    URL_PROFILE_IMAGE VARCHAR(255) DEFAULT '/path/to/default_profile_pic',
    USER_TYPE INT,
	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(ID_USER)
);

-- SCRIPTS TABLE: DONATION
-- TABLE 'DONATION'
CREATE TABLE `DONATION` (
    ID_DONATION INTEGER AUTO_INCREMENT NOT NULL,
    ID_DONATION_STATUS INTEGER NOT NULL,
    ID_DONATION_ITEM INTEGER NOT NULL,
    PRIMARY KEY(ID_DONATION),
    CONSTRAINT FK_DONATION_DONATION_STATUS FOREIGN KEY(ID_DONATION) REFERENCES DONATION_STATUS(ID_DONATION_STATUS),
    CONSTRAINT FK_DONATION_DONATION_ITEM FOREIGN KEY(ID_DONATION) REFERENCES DONATION_ITEM(ID_DONATION_ITEM)
);

-- TABLE 'DONATION_STATUS'
CREATE TABLE `DONATION_STATUS` (
    ID_DONATION_STATUS INTEGER AUTO_INCREMENT NOT NULL,
	`TYPE` ENUM('FAIL', 'DOING', 'DONE'),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(ID_DONATION_STATUS)
);

-- TABLE 'DONATION_ITEM'
CREATE TABLE `DONATION_ITEM` (
    ID_DONATION_ITEM INTEGER AUTO_INCREMENT NOT NULL,
    `TYPE` ENUM('VESTIMENTA', 'ALIMENTO', 'SAÚDE', 'HIGIENE', 'ANIMAL'),
    PRIMARY KEY(ID_DONATION_STATUS)
);

